apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  source:
    repoURL: https://github.com/wildOsprey/emerging-topics-in-politics.git
    targetRevision: main
    path: twapi/chart
