apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      values: |
        createCert: true
        antiAffinity: "soft"
        esJavaOpts: "-Xmx128m -Xms128m"
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: false
            xpack.security.transport.ssl.enabled: false

