apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipline-
spec:
  entrypoint: run
  templates:
  - name: scraper
    container:
      image: glapss/scraper:4
      args: ["--tweet-host", "twaapi-app.demo.svc.cluster.local:80", "--elastic-hosts", "https://elastic:password@elasticsearch-master.demo.svc.cluster.local:9200", "--tags", "#RussiaIsATerroristState,UkraineRussianWar,glorytoukraine,ukrainewar,Ukraine,#UA,#Ukraine", "--count", "100", "--times", "1000"]
  - name: ner
    container:
      image: glapss/ner:3
      args: ["--elastic-hosts", "https://elastic:OLVzrQ1YsIU91dIL@elasticsearch-master.demo.svc.cluster.local:9200", "--index", "demo_run"]
  - name: sentiment
    container:
      image: glapss/sentiment:1
      args: ["--elastic-hosts", "https://elastic:OLVzrQ1YsIU91dIL@elasticsearch-master.demo.svc.cluster.local:9200", "--index", "demo_run"]
  - name: topic-modelling
    container:
      image: glapss/topic-modelling:1
      args: ["--elastic-hosts", "https://elastic:OLVzrQ1YsIU91dIL@elasticsearch-master.demo.svc.cluster.local:9200", "--index", "demo_run"]
 
  - name: run
    steps:
    - - name: run-scraper
        template: scraper       
    - - name: run-ner 
        template: ner      
      - name: run-sentiment
        template: sentiment
      - name: run-topic-modelling
        template: topic-modelling

